name: cloud.gov Deploy

on:
  push:
    branches:
      - main
jobs:      
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with: 
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CG_USERNAME }}
          cf_password: ${{ secrets.CG_PASSWORD }}
          cf_command: v3-zdt-push dhs-sample
          cf_org: sandbox-gsa
          cf_space: mark.headd
